"""Bang chi so IDS (Precision, Recall, F1, MCC, FPR) tu run CPU. R1#3.

VI SAO. Phan bien 1 doi "Precision, Recall, F1-score, MCC, ROC-AUC, or False
Positive Rate". Thu tra loi HUA chung nam o ba bang cua ban thao, nhung doi chieu
cheo ngay 20/08/2026 cho thay tu "MCC" khong xuat hien o bat ky dau trong bai.
Phep tinh da co (derive_ids_metrics.py) nhung ket qua khong bao gio vao ban thao,
va script do lai doc results/runs, tuc du lieu RTX 4090 da bi thay the.

SUY, KHONG DOAN. Voi bai toan nhi phan, tu per_class_recall va accuracy da luu:
    FPR = 1 - recall_0
    n0/N = (acc - recall_1)/(recall_0 - recall_1)
    TN = n0*recall_0, FP = n0*(1-recall_0), TP = n1*recall_1, FN = n1*(1-recall_1)
roi MCC tu ma tran nham lan day du. Phep suy nay duoc KIEM: dung TP/FP tinh lai
precision va so voi per_class_precision da luu.

ROC-AUC KHONG suy duoc: no can diem so lien tuc, ma run chi luu nhan du doan.
Bai phai khai ro dieu do thay vi im lang.
"""
from __future__ import annotations
import csv, glob, json, math, re, statistics as st, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OLD = {11,17,23,29,31,37,42,43,2024,2026}
# Nhan NGAN: bang 7 cot khong vua mot cot IEEE (tran 22,4pt voi nhan day du).
CELLS = [("lrsweep_botiot","BoT-IoT"),("lrsweep_toniot","ToN-IoT"),
         ("lrsweep_cseciic","CSE-CIC")]
def derive(d):
    m=json.load(open(d+"/metrics.json"))["final_metrics"]
    rec=m["per_class_recall"]; pre=m["per_class_precision"]
    if len(rec)!=2: return None
    r0,r1=rec; acc=m["accuracy"]
    if abs(r0-r1)<1e-9: return None
    p0=(acc-r1)/(r0-r1)
    if not (0<=p0<=1): return None
    TN,FP,TP,FN=p0*r0,p0*(1-r0),(1-p0)*r1,(1-p0)*(1-r1)
    den=math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
    mcc=(TP*TN-FP*FN)/den if den>0 else float("nan")
    prec=TP/(TP+FP) if TP+FP>0 else float("nan")
    ok=abs(prec-pre[1])<0.02          # KIEM phep suy nguoc lai voi gia tri da luu
    return dict(prec=prec,rec=r1,f1=m["per_class_f1"][1],mcc=mcc,fpr=1-r0,ok=ok)
def main():
    L=["% Auto-generated by scripts/make_ids_metrics_table.py -- R1#3, run CPU",
       "\\begin{table}[t]","\\centering",
       ("\\caption{Detection metrics for the attack class, binary Dir($\\alpha{=}0.1$) at the "
        "shared $\\eta=10^{-2}$, ten seeds, mean $\\pm$ standard deviation. Precision, recall and "
        "F1 are stored per run; the false-positive rate and MCC are derived exactly from the "
        "stored per-class recalls and the accuracy, and the derivation is verified by "
        "reconstructing precision and comparing it against the stored value. ROC-AUC is not "
        "reported: it needs continuous scores and the runs store predicted labels only.}"),
       "\\label{tab:idsmetrics}","\\setlength{\\tabcolsep}{2.8pt}","\\footnotesize",
       "\\begin{tabular}{@{}llccccc@{}}","\\toprule",
       "Data & Arch. & Prec. & Rec. & F1 & MCC & FPR\\% \\\\","\\midrule"]
    nchk=nok=0
    for pre,name in CELLS:
        for arch,an in (("kan8","FedKAN-8"),("mlp80","MLP-PM-80")):
            rows=[]
            for d in glob.glob(str(ROOT/("results/%s/lrsweep_%s_lr0p01__dir0.1__seed*"%(pre,arch)))):
                m=re.search(r"seed(\d+)$",d)
                if not m or int(m.group(1)) not in OLD: continue
                r=derive(d)
                if r: rows.append(r); nchk+=1; nok+=r["ok"]
            if not rows: continue
            g=lambda k:(st.mean(x[k] for x in rows), st.stdev([x[k] for x in rows]))
            P,R,F,M,Fp=g("prec"),g("rec"),g("f1"),g("mcc"),g("fpr")
            L.append("%s & %s & $%.3f$ & $%.3f$ & $%.3f$ & $%.3f$ & $%.2f$ \\\\"%(
                name if arch=="kan8" else "",an,P[0],R[0],F[0],M[0],100*Fp[0]))
    L+=["\\bottomrule","\\end{tabular}","\\end{table}"]
    (ROOT/"results"/"tables"/"idsmetrics.tex").write_text("\n".join(L)+"\n",encoding="utf-8")
    print("  da ghi results/tables/idsmetrics.tex")
    print("  KIEM phep suy: %d/%d run tai lap dung precision da luu (sai so < 0,02)"%(nok,nchk))
    return 0 if nok==nchk else 1
if __name__=="__main__": sys.exit(main())
