"""Bang luoi lr DAY DU, ke ca eta = 0,3 va 1,0 (chang 0.3, 160 run).

VI SAO. Ban nop quet toi 1e-1 roi dung, va tu do bai rut ket luan "KAN ben voi lr
hon 2,7 den 5,4 lan". Con so do chi ton tai trong mot dai HEP quanh diem toi uu cua
KAN. Muc Threats cua ban truoc con viet "diem toi uu cua MLP nam o ria luoi... chua
nga ngu", trong khi 40 run tra loi dung cau do da nam tren dia tu lau ma khong duoc
bao cao (results/lrext/). Chang 0.3 chay them 120 run cho ba o con lai.

Ket qua: tren luoi day du, ti le MLP/KAN duoi 1 o CA BON o, tuc KAN kem ben hon.
"""
from __future__ import annotations
import csv, glob, re, statistics as st, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OLD = {11,17,23,29,31,37,42,43,2024,2026}
GRID = ["0p0003","0p001","0p003","0p01","0p03","0p1"]
LABEL = ["$3{\\times}10^{-4}$","$10^{-3}$","$3{\\times}10^{-3}$","$10^{-2}$","$3{\\times}10^{-2}$","$10^{-1}$","$3{\\times}10^{-1}$","$1$"]
CELLS = [("lrsweep_botiot","lrext","NF-BoT-IoT-v2 (bin.)"),
         ("lrsweep_toniot","lrext_toniot","NF-ToN-IoT-v2 (bin.)"),
         ("lrsweep_cseciic","lrext_cseciic","NF-CSE-CIC (bin.)"),
         ("lrsweep_cseciic_mc50k","lrext_cseciic_mc50k","NF-CSE-CIC (multi.)")]
def m5(d):
    a=[float(r["accuracy"]) for r in csv.DictReader(open(d+"/per_round.csv"))]
    return sum(a[-5:])/5
def pt(pat, filt=True):
    v=[m5(d) for d in glob.glob(str(ROOT/pat))
       if (not filt) or int(re.search(r"seed(\d+)$",d).group(1)) in OLD]
    return 100*st.mean(v) if v else None
def main():
    L=["% Auto-generated by scripts/make_lrwide_table.py -- 160 run cua chang 0.3",
       "\\begin{table*}[t]","\\centering",
       ("\\caption{Accuracy (\\%) across the full learning-rate grid, mean over the final five "
        "rounds and over ten seeds. The two rightmost columns were not swept by the first "
        "version's protocol. Over this range the parameter-matched MLP is the more robust of the "
        "two on every cell: the spread ratio $\\sigma_{\\text{MLP}}/\\sigma_{\\text{KAN}}$ is "
        "below one throughout.}"),
       "\\label{tab:lrwide}","\\renewcommand{\\arraystretch}{1.1}",
       "\\setlength{\\tabcolsep}{2.6pt}","\\scriptsize",
       "\\begin{tabular}{@{}ll"+"c"*8+"c@{}}","\\toprule",
       "Cell & Arch. & "+" & ".join(LABEL)+" & ratio \\\\","\\midrule"]
    for main_d, ext_d, name in CELLS:
        sp={}
        for arch,an in (("kan8","KAN-8"),("mlp80","MLP-PM-80")):
            vals=[pt("results/%s/lrsweep_%s_lr%s__dir0.1__seed*"%(main_d,arch,l)) for l in GRID]
            for tags in (("03","0p3"),("10","1","1p0")):
                got=None
                for tg in tags:
                    got=pt("results/%s/lrext_%s_lr%s__dir0.1__seed*"%(ext_d,arch,tg), filt=False)
                    if got is not None: break
                vals.append(got)
            ok=[v for v in vals if v is not None]
            sp[arch]=max(ok)-min(ok)
            L.append("%s & %s & %s & %s \\\\"%(name if arch=="kan8" else "", an,
                     " & ".join("%.1f"%v if v is not None else "--" for v in vals),
                     "" if arch=="kan8" else "$%.2f$"%(sp["mlp80"]/sp["kan8"])))
        L.append("\\addlinespace[2pt]")
    L+=["\\bottomrule","\\end{tabular}","\\end{table*}"]
    (ROOT/"results"/"tables"/"lrwide.tex").write_text("\n".join(L)+"\n",encoding="utf-8")
    print("  da ghi results/tables/lrwide.tex")
    return 0
if __name__=="__main__": sys.exit(main())
