"""Byte VA VONG toi dich, tu run CPU. R1#4.

VI SAO SUA. (a) Thu tra loi R1.4 hua bao cao "bytes-to-target and rounds-to-target",
nhung bang chi co cot MB va so seed; tu "rounds" khong co trong bang. (b) Bang cu
sinh tu du lieu RTX 4090. (c) Hang FedKAN-8 KHONG DON DIEU: 1,32 MB de dat dich 90%
nhung 1,04 MB de dat dich 94% chat hon. Do la hien vat cua viec lay trung binh tren
CAC SEED DAT DICH: 9/10 seed dat 90% con 8/10 dat 94%, va seed rot ra la seed cham.
Bang cu canh bao chung chung ve chuyen do nhung khong chi ra chinh hang cua no.
"""
from __future__ import annotations
import csv, glob, re, statistics as st, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OLD = {11,17,23,29,31,37,42,43,2024,2026}
ARCH = [("kan8","FedKAN-8"),("kan16","F-KAN-16"),("mlp32","MLP-32"),("mlp80","MLP-PM-80")]
def rows_of(arch):
    o={}
    for d in glob.glob(str(ROOT/("results/lrsweep_botiot/lrsweep_%s_lr0p01__dir0.1__seed*"%arch))):
        m=re.search(r"seed(\d+)$",d)
        if m and int(m.group(1)) in OLD:
            o[int(m.group(1))]=list(csv.DictReader(open(d+"/per_round.csv")))
    return o
def main():
    data={a:rows_of(a) for a,_ in ARCH}
    best=max(max(float(r["accuracy"]) for r in rr) for v in data.values() for rr in v.values())
    L=["% Auto-generated by scripts/make_bytes2target_table.py -- run CPU",
       "\\begin{table}[t]","\\centering",
       ("\\caption{Uplink and rounds needed to \\emph{reach} a target, rather than after a fixed "
        "round budget. The target is a fraction of the best accuracy any architecture reaches in "
        "this cell (%.2f\\%%). The ``seeds'' column is the honest part, and it explains an "
        "inversion in the FedKAN-8 row: the mean is taken over the seeds that arrive, so a "
        "stricter target can look cheaper when the slowest seed drops out of the average. Rows "
        "are not comparable across targets unless the seed counts match.}"%(100*best)),
       "\\label{tab:bytes2target}","\\setlength{\\tabcolsep}{3.4pt}","\\footnotesize",
       "\\begin{tabular}{@{}lcccccc@{}}","\\toprule",
       "Model & \\multicolumn{3}{c}{$90\\%$ of best} & \\multicolumn{3}{c}{$94\\%$ of best} \\\\",
       "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
       " & MB & rounds & seeds & MB & rounds & seeds \\\\","\\midrule"]
    for a,nm in ARCH:
        cells=[]
        for frac in (0.90,0.94):
            tgt=frac*best; mbs=[]; rds=[]; n=0
            for rr in data[a].values():
                acc=0.0
                for i,r in enumerate(rr,1):
                    acc+=float(r["comm_uplink_bytes"])
                    if float(r["accuracy"])>=tgt:
                        mbs.append(acc/1e6); rds.append(i); n+=1; break
            cells += ["%.2f"%st.mean(mbs) if mbs else "--",
                      "%.1f"%st.mean(rds) if rds else "--",
                      "%d/%d"%(n,len(data[a]))]
        L.append("%s & %s \\\\"%(nm," & ".join(cells)))
    L+=["\\bottomrule","\\end{tabular}","\\end{table}"]
    (ROOT/"results"/"tables"/"bytes2target.tex").write_text("\n".join(L)+"\n",encoding="utf-8")
    print("  da ghi results/tables/bytes2target.tex (them cot rounds)")
    return 0
if __name__=="__main__": sys.exit(main())
