"""Sinh lai bang chinh TU RUN TREN MOT MAY, thay bang cu tron hai phan cung.

VI SAO PHAI VIET LAI. Bang I/III/V/VI cua ban nop sinh tu `results/runs`, chay tren
RTX 4090. Cac bang moi cua vong R1 sinh tu `results/lrsweep_*` va `results/lowhet`,
chay tren Apple M5. Cover letter lai viet "moi thi nghiem deu chay lai tren MOT may".
Cau do SAI khi bang van tron hai nguon. Cong `check_artifact_hygiene` khong bat duoc
vi no khong doc `device` trong tung run.

Script nay chi doc run tren MOT may va IN RA thiet bi de nguoi doc kiem duoc.

KHAI THUOC DO NGAY TRONG CAPTION. Bang cu ghi "Final-round accuracy" con bang moi
dung trung binh 5 vong cuoi, va khong bang nao noi ro, nen bon o cua Bang VII lech
Bang III/V/VI ma khong ai giai thich duoc. Nay moi caption deu ghi thuoc do.
"""
from __future__ import annotations
import csv
import glob
import json
import re
import statistics as st
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results" / "tables_r1"

ARCH = [("mlp32", "FedAvg-MLP (32h)", 1346),
        ("mlp80", "FedAvg-MLP-PM (80h)", 3362),
        ("kan8", "FedKAN (8h)", 3280),
        ("kan16", "F-KAN (16h)", 6560)]


def series(d):
    a = [float(r["accuracy"]) for r in csv.DictReader(open(d + "/per_round.csv"))]
    return a


def cell(pat, seeds=None):
    """Tra ve dict seed -> (mean5, last, device)."""
    o = {}
    for d in glob.glob(str(ROOT / pat)):
        m = re.search(r"seed(\d+)", d)
        if not m:
            continue
        s = int(m.group(1))
        if seeds is not None and s not in seeds:
            continue
        try:
            a = series(d)
            dev = json.load(open(d + "/metrics.json")).get("device", "?")
            o[s] = (sum(a[-5:]) / 5, a[-1], dev)
        except Exception:
            pass
    return o


OLD = {11, 17, 23, 29, 31, 37, 42, 43, 2024, 2026}


def fmt(v):
    return "%.2f" % (100 * v)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    devs = set()
    rows = []
    for key, label, npar in ARCH:
        r = {"label": label, "params": npar}
        for tag, pat in [("iid", "results/lowhet/lowhet_%s__iid__seed*" % key),
                         ("a1", "results/lowhet/lowhet_%s__dir1.0__seed*" % key),
                         ("a01", "results/lrsweep_botiot/lrsweep_%s_lr0p01__dir0.1__seed*" % key)]:
            c = cell(pat, OLD)
            if not c:
                r[tag] = None
                continue
            devs |= {v[2] for v in c.values()}
            m5 = [v[0] for v in c.values()]
            r[tag] = (st.mean(m5), st.stdev(m5) if len(m5) > 1 else 0.0, len(m5),
                      st.mean(v[1] for v in c.values()))
        rows.append(r)

    if len(devs) > 1:
        print("  ⛔ CANH BAO: cac run den tu NHIEU thiet bi: %s" % sorted(devs))
        print("     Bang tron hai phan cung thi khong duoc noi 'chay tren mot may'.")
    else:
        print("  ✅ moi run cua bang nay tu MOT thiet bi: %s" % (sorted(devs) or ["?"])[0])

    best = {}
    for tag in ("iid", "a1", "a01"):
        vals = [(r[tag][0], r["label"]) for r in rows if r.get(tag)]
        if vals:
            best[tag] = max(vals)[1]

    # MOT bang, HAI thuoc do canh nhau. Truoc 21/08 day la hai bang rieng
    # (headline_r1 va lastround_r1) in cung mot bo run; doc cheo giua hai bang la
    # viec cua nguoi doc. Gop lai vua tiet kiem mot bang vua lam CHENH LECH giua
    # hai thuoc do hien ra ngay tren cung mot dong, ma do chinh la noi dung.
    dev = (sorted(devs) or ["?"])[0]
    lines = [
        "% Auto-generated by scripts/make_tables_r1.py -- MOT may, HAI thuoc do",
        "\\begin{table*}[t]", "\\centering",
        ("\\caption{Accuracy (\\%) on NF-BoT-IoT-v2 binary detection under three heterogeneity "
         "regimes, ten seeds, all runs on one machine (" + dev + "). Each cell gives the "
         "\\emph{mean over the final five rounds} and, in grey, the \\emph{last round alone}, "
         "the estimator the first version used. The difference between them is the cost of that "
         "choice; end-of-training oscillation over the last ten rounds is $2.1$--$2.7$~pp. "
         "\\textbf{Bold} = best mean per column.}"),
        "\\label{tab:headline_r1}",
        "\\renewcommand{\\arraystretch}{1.15}",
        "\\setlength{\\tabcolsep}{3pt}", "\\footnotesize",
        "\\begin{tabular}{@{}lrccc@{}}", "\\toprule",
        "Method & Params & IID & Dir($\\alpha{=}1.0$) & Dir($\\alpha{=}0.1$) \\\\",
        "\\midrule",
    ]
    for r in rows:
        cells = []
        for tag in ("iid", "a1", "a01"):
            if not r.get(tag):
                cells.append("--")
                continue
            mu, sd, n, last = r[tag]
            s = "%s\\,{\\scriptsize$\\pm$%.2f}" % (fmt(mu), 100 * sd)
            if best.get(tag) == r["label"]:
                s = "\\textbf{%s}" % s
            cells.append(s + " {\\scriptsize\\textcolor{gray}{%s}}" % fmt(last))
        lines.append("%s & %s & %s \\\\" % (r["label"], "{:,}".format(r["params"]), " & ".join(cells)))
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    (OUT / "headline_r1.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    for f in ("lastround_r1", "headline_botiot"):
        q = OUT / (f + ".tex")
        if q.exists():
            q.unlink()

    print("  da ghi %s" % (OUT / "headline_r1.tex").relative_to(ROOT))
    print("  da ghi %s" % (OUT / "lastround_r1.tex").relative_to(ROOT))
    for r in rows:
        if r.get("a01"):
            mu, sd, n, last = r["a01"]
            print("    %-22s Dir0.1: TB5 %.2f%% (sd %.2f, n=%d) | vong cuoi %.2f%%"
                  % (r["label"], 100 * mu, 100 * sd, n, 100 * last))


if __name__ == "__main__":
    sys.exit(main())
