"""Bang thuat toan tong hop, SINH TU DU LIEU va co cot p.

VI SAO. Bang nay truoc day go tay va chu thich hua "$p$ is paired against FedAvg for
the same architecture", nhung bang KHONG CO cot p. Cung luc do thu tra loi R1.2/R2.2
lai trich p = 0,32 / 0,55 / 0,003 cho phan bien doc. Ba tai lieu, ba trang thai khac
nhau ve cung mot dai luong. Phat hien khi doi chieu cheo ngay 20/08/2026.

Them ca hang SCAFFOLD duoi SGD (chang 0.4): bai TU NEU gia thuyet "hong vi Adam" ma
khong kiem; do roi thi duoi SGD te hon, sd = 0.
"""
from __future__ import annotations
import csv, glob, math, re, statistics as st, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def m5(d):
    a=[float(r["accuracy"]) for r in csv.DictReader(open(d+"/per_round.csv"))]
    return sum(a[-5:])/5
def upl(d):
    r=list(csv.DictReader(open(d+"/per_round.csv")))
    # comm_uplink_bytes DA la tong cua ca 10 client trong mot vong. Lan dau toi
    # nhan them 10 va ra 76,88 MB thay vi 7,69: kiem bang cach cong tay mot run.
    return sum(float(x["comm_uplink_bytes"]) for x in r) / 1e6
# CHI 10 seed goc. Tu 21/08 thu muc lrsweep_botiot con chua 20 seed giu rieng
# (101-120) cua giao thuc long nhau; khong loc thi moc FedAvg gop 30 seed va ra
# 94,66 +- 4,85 thay vi 94,22 +- 5,61. Bat duoc bang cach doi chieu voi macro.
OLD={11,17,23,29,31,37,42,43,2024,2026}
def seeds(pat):
    o={}
    for d in glob.glob(str(ROOT/pat)):
        m=re.search(r"seed(\d+)$",d)
        if m and int(m.group(1)) in OLD:
            try: o[int(m.group(1))]=(m5(d),upl(d))
            except: pass
    return o
def paired_p(d):
    n=len(d); s=st.stdev(d) if n>1 else 0
    if n<2 or s==0: return float("nan")
    t=abs(st.mean(d))/(s/n**0.5); df=n-1; x=df/(df+t*t)
    def bcf(a,b,x):
        c,dd=1.0,1.0-(a+b)*x/(a+1.0); dd=1.0/(dd if abs(dd)>1e-300 else 1e-300); h=dd
        for m in range(1,300):
            m2=2*m
            aa=m*(b-m)*x/((a-1.0+m2)*(a+m2)); dd=1.0/(1.0+aa*dd if abs(1.0+aa*dd)>1e-300 else 1e-300)
            c=1.0+aa/c; h*=dd*c
            aa=-(a+m)*(a+b+m)*x/((a+m2)*(a+1.0+m2)); dd=1.0/(1.0+aa*dd if abs(1.0+aa*dd)>1e-300 else 1e-300)
            c=1.0+aa/c; de=dd*c; h*=de
            if abs(de-1.0)<3e-16: break
        return h
    def bi(a,b,x):
        if x<=0: return 0.0
        if x>=1: return 1.0
        lb=(math.lgamma(a+b)-math.lgamma(a)-math.lgamma(b)+a*math.log(x)+b*math.log(1-x))
        return math.exp(lb)*bcf(a,b,x)/a if x<(a+1)/(a+b+2) else 1.0-math.exp(lb)*bcf(b,a,1-x)/b
    return bi(df/2.0,0.5,x)
ALGOS=[("__base__","FedAvg"),("fedprox","FedProx"),("moon","MOON"),("fedpaq","FedPAQ"),("scaffold","SCAFFOLD")]
def main():
    L=["% Auto-generated by scripts/make_algos_table.py",
       "\\begin{table}[t]","\\centering",
       ("\\caption{Aggregation and compression algorithms on NF-BoT-IoT-v2 binary, "
        "Dir $\\alpha=0.1$, shared $\\eta=10^{-2}$, ten seeds. Accuracy is the mean over the "
        "final five rounds; $p$ is the paired $t$-test against FedAvg for the same "
        "architecture. The last row tests, and rejects, the explanation we previously offered "
        "for SCAFFOLD without testing it.}"),
       "\\label{tab:algos}","\\setlength{\\tabcolsep}{3.4pt}","\\footnotesize",
       "\\begin{tabular}{@{}llcccc@{}}","\\toprule",
       "Algorithm & Arch. & Accuracy & $\\sigma$ & Uplink (MB) & $p$ \\\\","\\midrule"]
    for arch,an in (("kan8","KAN-8"),("mlp80","MLP-PM-80")):
        # KHONG co run "fedavg" trong results/algos/. Moc FedAvg chinh la run o lr
        # CHUNG cua lrsweep: cung thuat toan, cung sieu tham so, cung seed. Lan dau
        # toi glob vao algos/ va duoc tap rong, nen cot p ra "--" het ma bang van in.
        base=seeds("results/lrsweep_botiot/lrsweep_%s_lr0p01__dir0.1__seed*"%arch)
        for al,nm in ALGOS:
            s = base if al=="__base__" else seeds("results/algos/algo_%s_%s__*"%(al,arch))
            if not s: continue
            acc=[v[0] for v in s.values()]; up=st.mean(v[1] for v in s.values())
            sp=sorted(set(s)&set(base))
            p=paired_p([s[x][0]-base[x][0] for x in sp]) if al!="__base__" and sp else None
            best = al=="fedprox"
            f=lambda x:("\\mathbf{%s}"%x) if best else x
            L.append("%s & %s & $%s$ & $%s$ & $%.2f$ & %s \\\\"%(
                nm,an,f("%.2f"%(100*st.mean(acc))),f("%.2f"%(100*st.stdev(acc))),up,
                "--" if p is None else ("$%.3f$"%p)))
        if arch=="kan8": L.append("\\midrule")
    # hang SCAFFOLD duoi SGD
    L.append("\\midrule")
    for arch,an in (("kan8","KAN-8"),("mlp80","MLP-PM-80")):
        s=seeds("results/scaffold_sgd/scaffold_sgd_%s__*"%arch)
        if s:
            acc=[v[0] for v in s.values()]
            L.append("SCAFFOLD (SGD) & %s & $%.2f$ & $%.2f$ & $%.2f$ & -- \\\\"%(
                an,100*st.mean(acc),100*st.stdev(acc),st.mean(v[1] for v in s.values())))
    L+=["\\bottomrule","\\end{tabular}","\\end{table}"]
    (ROOT/"results"/"tables"/"algos.tex").write_text("\n".join(L)+"\n",encoding="utf-8")
    print("  da ghi results/tables/algos.tex")
    return 0
if __name__=="__main__": sys.exit(main())
