"""Emit publication-ready LaTeX tables from results/aggregated/.

Output: results/tables/headline_botiot.tex      (main results table)
        results/tables/worst_seed_botiot.tex    (robustness table)
"""
from __future__ import annotations
import json
import statistics as stats
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / "results" / "runs"
OUT = ROOT / "results" / "tables"


VARIANT_ORDER = ["mlp_h32", "mlp_h80", "kan_h8", "kan_h16"]
VARIANT_LABEL = {
    "mlp_h32":  r"FedAvg-MLP (32h)",
    "mlp_h80":  r"FedAvg-MLP-PM (80h)",
    "kan_h8":   r"\textbf{FedKAN (Ours, 8h)}",
    "kan_h16":  r"F-KAN (16h)",
}
PARTITION_ORDER = ["iid", "dir1.0", "dir0.1"]
PARTITION_HEAD = {
    "iid": "IID",
    "dir1.0": r"Dir($\alpha{=}1.0$)",
    "dir0.1": r"Dir($\alpha{=}0.1$)",
}


DATASET_PREFIX = "e1_botiot"   # BoT-IoT only for the headline tables


def load_runs() -> list[dict]:
    out = []
    for d in sorted(RUNS.iterdir()):
        if not d.is_dir() or d.name.startswith("smoke"):
            continue
        if not d.name.startswith(DATASET_PREFIX):
            continue
        mj = d / "metrics.json"
        if not mj.exists():
            continue
        m = json.loads(mj.read_text())
        out.append(m)
    return out


def variant_of(m: dict) -> str | None:
    name = m.get("model_name")
    h = m.get("model_hidden")
    if not name or not h:
        return None
    return f"{name}_h{'x'.join(str(x) for x in h)}"


def ptag_of(m: dict) -> str:
    p = m.get("data_partition", "dirichlet")
    if p == "iid":
        return "iid"
    a = m.get("data_alpha")
    return f"dir{a}"


def aggregate_by(metric: str) -> dict:
    """{(mode, variant, ptag): {'mean': X, 'std': Y, 'min': Z, 'n': N, 'params': P}}"""
    bucket: dict = {}
    for m in load_runs():
        v = variant_of(m)
        if v is None:
            continue
        key = (m.get("data_mode", "binary"), v, ptag_of(m))
        bucket.setdefault(key, {"vals": [], "params": m.get("n_params")})
        fm = m.get("final_metrics", {})
        if metric in fm:
            bucket[key]["vals"].append(fm[metric])
    out = {}
    for k, v in bucket.items():
        if not v["vals"]:
            continue
        out[k] = {
            "mean": stats.mean(v["vals"]),
            "std": stats.stdev(v["vals"]) if len(v["vals"]) > 1 else 0.0,
            "min": min(v["vals"]),
            "max": max(v["vals"]),
            "n": len(v["vals"]),
            "params": v["params"],
        }
    return out


def fmt_pct(mean: float, std: float, *, bold: bool = False) -> str:
    s = f"{mean*100:.2f}\\,{{\\scriptsize$\\pm${std*100:.2f}}}"
    return r"\textbf{" + s + "}" if bold else s


def headline_table(metric: str = "accuracy") -> str:
    data = aggregate_by(metric)
    modes = ["binary", "multiclass"]
    lines = []
    lines.append(r"% Auto-generated by scripts/make_latex_tables.py")
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Final-round accuracy (\%) on NF-BoT-IoT-v2 under three data-heterogeneity regimes. Mean $\pm$ std over $n$ seeds. \textbf{Bold} = best mean per column. KAN-8 and MLP-PM-80 are matched in parameter count ($\sim$3.3k).}")
    lines.append(r"\label{tab:headline_botiot}")
    lines.append(r"\renewcommand{\arraystretch}{1.15}")
    lines.append(r"\begin{tabular}{l c c " + " ".join(["c"] * len(PARTITION_ORDER) * len(modes)) + "}")
    lines.append(r"\toprule")
    head1 = ["Method", "Params", "Comm. (MB)"]
    for mode in modes:
        head1 += [r"\multicolumn{" + str(len(PARTITION_ORDER)) + r"}{c}{" + mode.capitalize() + "}"]
    lines.append(" & ".join(head1) + r" \\")
    span_cmds = []
    pos = 4
    for _ in modes:
        span_cmds.append(fr"\cmidrule(lr){{{pos}-{pos+len(PARTITION_ORDER)-1}}}")
        pos += len(PARTITION_ORDER)
    lines.append(" ".join(span_cmds))
    sub = ["", "", ""]
    for _ in modes:
        sub += [PARTITION_HEAD[p] for p in PARTITION_ORDER]
    lines.append(" & ".join(sub) + r" \\")
    lines.append(r"\midrule")

    # Compute "best mean" per column for bold marking.
    best_per_col: dict = {}
    for mode in modes:
        for ptag in PARTITION_ORDER:
            vals = [(v, data.get((mode, v, ptag), {}).get("mean", -1))
                    for v in VARIANT_ORDER if (mode, v, ptag) in data]
            if vals:
                best_per_col[(mode, ptag)] = max(vals, key=lambda x: x[1])[0]

    # Estimate Comm column: sum bytes_per_round_uplink_per_client * 2 * K * R / 1e6 if avail.
    # Easier: compute total_uplink_bytes mean across all runs per variant.
    comm = {}
    for m in load_runs():
        v = variant_of(m)
        if v is None:
            continue
        comm.setdefault(v, []).append(m.get("total_uplink_bytes", 0) / 1024 / 1024)
    comm_mean = {v: stats.mean(vals) if vals else 0 for v, vals in comm.items()}

    for v in VARIANT_ORDER:
        params = next((data[(m, v, p)]["params"] for m in modes for p in PARTITION_ORDER
                       if (m, v, p) in data), 0)
        row = [VARIANT_LABEL[v], f"{params:,}", f"{comm_mean.get(v, 0):.2f}"]
        for mode in modes:
            for ptag in PARTITION_ORDER:
                cell = data.get((mode, v, ptag))
                if cell is None:
                    row.append("--")
                else:
                    bold = best_per_col.get((mode, ptag)) == v
                    row.append(fmt_pct(cell["mean"], cell["std"], bold=bold))
        lines.append(" & ".join(row) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table*}")
    return "\n".join(lines) + "\n"


def worst_seed_table() -> str:
    """Robustness lens: the WORST seed's accuracy. Highlights MLP collapse."""
    data = aggregate_by("accuracy")
    lines = []
    lines.append(r"% Auto-generated by scripts/make_latex_tables.py")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Worst-seed accuracy (\%) — the weakest of $n$ seeds per cell. Reveals catastrophic collapse hidden by averages. NF-BoT-IoT-v2 binary, 50 rounds.}")
    lines.append(r"\label{tab:worst_seed_botiot}")
    lines.append(r"\renewcommand{\arraystretch}{1.15}")
    lines.append(r"\setlength{\tabcolsep}{4pt}")
    lines.append(r"\begin{tabular}{@{}l c " + " ".join(["c"] * len(PARTITION_ORDER)) + r"@{}}")
    lines.append(r"\toprule")
    head = ["Method", "Params"] + [PARTITION_HEAD[p] for p in PARTITION_ORDER]
    lines.append(" & ".join(head) + r" \\")
    lines.append(r"\midrule")
    for v in VARIANT_ORDER:
        params = next((data[("binary", v, p)]["params"]
                       for p in PARTITION_ORDER if ("binary", v, p) in data), 0)
        row = [VARIANT_LABEL[v], f"{params:,}"]
        for p in PARTITION_ORDER:
            cell = data.get(("binary", v, p))
            if cell is None:
                row.append("--")
            else:
                row.append(f"{cell['min']*100:.2f}")
        lines.append(" & ".join(row) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "headline_botiot.tex").write_text(headline_table(), encoding="utf-8")
    (OUT / "worst_seed_botiot.tex").write_text(worst_seed_table(), encoding="utf-8")
    print(f"Wrote {OUT/'headline_botiot.tex'}")
    print(f"Wrote {OUT/'worst_seed_botiot.tex'}")
    print()
    print("=" * 76)
    print("WORST-SEED ROBUSTNESS (binary, accuracy %)")
    print("=" * 76)
    data = aggregate_by("accuracy")
    print(f"{'Variant':18s} {'Params':>7s}  " +
          "  ".join(f"{PARTITION_HEAD[p].replace('$',''):>16s}" for p in PARTITION_ORDER))
    print("-" * 76)
    for v in VARIANT_ORDER:
        params = next((data[("binary", v, p)]["params"]
                       for p in PARTITION_ORDER if ("binary", v, p) in data), 0)
        cells = []
        for p in PARTITION_ORDER:
            c = data.get(("binary", v, p))
            cells.append(f"{c['min']*100:>16.2f}" if c else f"{'-':>16s}")
        print(f"{v:18s} {params:>7d}  " + "  ".join(cells))


if __name__ == "__main__":
    main()
