"""Bang worst-seed, sinh tu run CPU, va THEM cot lr rieng de lo ra cho DAO DAU.

VI SAO PHAI THEM COT. Ban nop bao "+24,24 pp loi the worst-seed" tren NF-BoT-IoT-v2
va goi do la bang chung cho co che kien truc. Ban sua rut tuyen bo do, nhung chi rut
VI LY DO CHON LOC: cung phep so cho -11,07 va -21,23 tren hai bo kia, nen quoting cai
thu ba la mot phep chon.

Do lai ngay 20/08 thi ly do that con nang hon: cho MOI BEN lr rieng, MLP-PM-80 di tu
56,42 len 81,26 va khoang cach DAO thanh -1,89 pp. Tuc con so +24,24 khong song sot
qua viec dò lr, chu khong phai chi la mot phep chon may man.

Mot bang chi in cot "lr chung" khong the hien duoc dieu do. Bang nay in CA HAI cot
canh nhau, va do chinh la noi dung can noi.

Nguon: results/lrsweep_<bo>/ (lr chung 0p01 va lr tot nhat tung ben), results/lowhet/
cho hai o IID va Dir1.0.
"""
from __future__ import annotations
import csv
import glob
import json
import re
import statistics as st
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results" / "tables"
OLD = {11, 17, 23, 29, 31, 37, 42, 43, 2024, 2026}
GRID = ["0p0003", "0p001", "0p003", "0p01", "0p03", "0p1"]
# Nhan NGAN cho bang mot cot IEEE: ban dai lam bang 6 cot tran khung 11,9pt.
ARCH = [("mlp32", "MLP-32", 1346), ("mlp80", "MLP-PM-80", 3362),
        ("kan8", "\\textbf{FedKAN-8}", 3280), ("kan16", "F-KAN-16", 6560)]
ARCH_LONG = {"mlp32": "FedAvg-MLP (32h)", "mlp80": "FedAvg-MLP-PM (80h)",
             "kan8": "\\textbf{FedKAN (Ours, 8h)}", "kan16": "F-KAN (16h)"}
CELLS = [("lrsweep_botiot", "NF-BoT-IoT-v2"), ("lrsweep_toniot", "NF-ToN-IoT-v2"),
         ("lrsweep_cseciic", "NF-CSE-CIC-IDS2018-v2")]


def m5(d):
    a = [float(r["accuracy"]) for r in csv.DictReader(open(d + "/per_round.csv"))]
    return sum(a[-5:]) / 5


def seeds_of(pre, arch, lr):
    o = {}
    for d in glob.glob(str(ROOT / ("results/%s/lrsweep_%s_lr%s__dir0.1__seed*" % (pre, arch, lr)))):
        m = re.search(r"seed(\d+)$", d)
        if m and int(m.group(1)) in OLD:
            try:
                o[int(m.group(1))] = m5(d)
            except Exception:
                pass
    return o


def best_lr(pre, arch):
    c = [(st.mean(seeds_of(pre, arch, lr).values()), lr) for lr in GRID if seeds_of(pre, arch, lr)]
    return max(c)[1] if c else None


def lowhet(arch, reg):
    v = [m5(d) for d in glob.glob(str(ROOT / ("results/lowhet/lowhet_%s__%s__seed*" % (arch, reg))))]
    return min(v) if v else None


def main():
    dev = {json.load(open(f)).get("device", "?")
           for f in glob.glob(str(ROOT / "results/lrsweep_botiot/*/metrics.json"))[:50]}
    if dev != {"cpu"}:
        print("  ⛔ nguon khong thuan CPU: %s" % sorted(dev))
        return 1

    # ---------- bang 1: worst-seed tren BoT-IoT, ba che do, + cot lr rieng ------
    L = ["% Auto-generated by scripts/worst_seed_cpu.py -- run CPU",
         "\\begin{table}[t]", "\\centering",
         ("\\caption{Worst-seed accuracy (\\%) on NF-BoT-IoT-v2 binary detection, the weakest of "
          "ten seeds, measured as the mean over the final five rounds. The last two columns are "
          "the point of the table: at the shared step size the parameter-matched MLP collapses, "
          "and at each architecture's own best step size it does not. The collapse is a property "
          "of the tuning, not of the architecture.}"),
         "\\label{tab:worst_seed_botiot}",
         "\\renewcommand{\\arraystretch}{1.15}", "\\setlength{\\tabcolsep}{4pt}", "\\footnotesize",
         "\\begin{tabular}{@{}l r c c c c@{}}", "\\toprule",
         "& & & & \\multicolumn{2}{c}{Dir($\\alpha{=}0.1$)} \\\\",
         "\\cmidrule(lr){5-6}",
         "Method & Params & IID & Dir 1.0 & shared $\\eta$ & tuned $\\eta$ \\\\",
         "\\midrule"]
    ws = {}
    for a, lab, npar in ARCH:
        iid, d10 = lowhet(a, "iid"), lowhet(a, "dir1.0")
        sh = seeds_of("lrsweep_botiot", a, "0p01")
        bl = best_lr("lrsweep_botiot", a)
        tu = seeds_of("lrsweep_botiot", a, bl)
        ws[a] = (min(sh.values()) if sh else None, min(tu.values()) if tu else None)
        L.append("%s & %s & %s & %s & %s & %s \\\\" % (
            lab, "{:,}".format(npar),
            "%.2f" % (100 * iid) if iid else "--", "%.2f" % (100 * d10) if d10 else "--",
            "%.2f" % (100 * ws[a][0]) if ws[a][0] else "--",
            "%.2f" % (100 * ws[a][1]) if ws[a][1] else "--"))
    L.append("\\midrule")
    g_sh = 100 * (ws["kan8"][0] - ws["mlp80"][0])
    g_tu = 100 * (ws["kan8"][1] - ws["mlp80"][1])
    L += ["\\multicolumn{4}{@{}l}{KAN-8 worst-seed advantage over MLP-PM-80} & $%+.2f$ & $%+.2f$ \\\\"
          % (g_sh, g_tu),
          "\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT / "worst_seed_botiot.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("  da ghi results/tables/worst_seed_botiot.tex")
    print("     loi the worst-seed: lr chung %+.2f pp  ->  lr rieng %+.2f pp  (DAO DAU)" % (g_sh, g_tu))

    # ---------- bang 2: worst-seed qua ba bo du lieu ---------------------------
    L = ["% Auto-generated by scripts/worst_seed_cpu.py -- run CPU",
         "\\begin{table*}[t]", "\\centering",
         ("\\caption{Worst-seed accuracy (\\%) under Dir($\\alpha{=}0.1$) across the three "
          "datasets, at the shared $\\eta=10^{-2}$ of the original protocol. The first version of "
          "this manuscript quoted the NF-BoT-IoT-v2 column alone. The other two columns run the "
          "other way, and Table~\\ref{tab:worst_seed_botiot} shows that even the first one does "
          "not survive per-architecture tuning.}"),
         "\\label{tab:cross_dataset}",
         "\\renewcommand{\\arraystretch}{1.15}", "\\setlength{\\tabcolsep}{6pt}", "\\footnotesize",
         "\\begin{tabular}{@{}l r c c c@{}}", "\\toprule",
         "Method & Params & " + " & ".join(n for _, n in CELLS) + " \\\\", "\\midrule"]
    W = {}
    for a, lab, npar in ARCH:
        cells = []
        for pre, _ in CELLS:
            s = seeds_of(pre, a, "0p01")
            v = min(s.values()) if s else None
            W[(a, pre)] = v
            cells.append("%.2f" % (100 * v) if v else "--")
        L.append("%s & %s & %s \\\\" % (ARCH_LONG[a], "{:,}".format(npar), " & ".join(cells)))
    L.append("\\midrule")
    adv = []
    for pre, _ in CELLS:
        adv.append("$%+.2f$\\,pp" % (100 * (W[("kan8", pre)] - W[("mlp80", pre)])))
    L += ["\\multicolumn{2}{@{}l}{KAN-8 advantage over MLP-PM-80} & " + " & ".join(adv) + " \\\\",
          "\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    (OUT / "cross_dataset_placeholder.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("  da ghi results/tables/cross_dataset_placeholder.tex")
    print("     loi the worst-seed qua ba bo: %s" % " ".join(a.replace("$", "") for a in adv))
    return 0


if __name__ == "__main__":
    sys.exit(main())
